### ISSUE TITLE
Optimize eval_metrics runtime

### ISSUE THREAD

**Issue by Innixma** [Innixma/autogluon-zeroshot#20]
Optimizing eval_metric speed is critical to speeding up simulations, particular for ensemble simulations.

Currently `eval_metric` calls make up >90% of the total runtime.

# Which eval_metrics

Currently, AutoGluon implementations of `rmse` (regression), `log_loss` (multiclass) and `roc_auc` (binary).

## rmse

[rmse implementation](https://github.com/autogluon/autogluon/blob/1872a496284987853fd920283b5638f038b8552b/core/src/autogluon/core/metrics/__init__.py#L457-L468)

### Progress

Major speedup by simply adding `@jit(nopython=True)` decorator, which leads to around a 4x+ speedup with ray:

```python3
from numba import jit


@jit(nopython=True)
def fast_rmse_func(y_true, y_pred):
    return np.sqrt(((y_true - y_pred) ** 2).mean())

root_mean_squared_error = make_scorer('root_mean_squared_error',
                                      # rmse_func,
                                      fast_rmse_func,
                                      optimum=0,
                                      greater_is_better=False)
root_mean_squared_error.add_alias('rmse')

```

## logloss

[logloss implementation](https://github.com/autogluon/autogluon/blob/1872a496284987853fd920283b5638f038b8552b/core/src/autogluon/core/metrics/__init__.py#L514-L553)

### Progress

Likely large speed ups can be made, as we are using sklearn currently which has many redundant checks
- Of particular note is the transformation of y_true every call (https://github.com/scikit-learn/scikit-learn/blob/364c77e047ca08a95862becf40a04fe9d4cd2c98/sklearn/metrics/_classification.py#L2593). We might get a huge speedup if we only transform y_true once and then pass the transformed y_true into every call for a given Greedy Weighted Ensemble.

## roc_auc

[roc_auc implementation](https://github.com/autogluon/autogluon/blob/1872a496284987853fd920283b5638f038b8552b/core/src/autogluon/core/metrics/classification_metrics.py#L373-L441)
- Note: This `roc_auc` implementation is 5x faster than native scikit-learn, but likely could be faster if using C implementation (ex: Cython)
- Potential fast version: https://github.com/jfpuget/metrics/blob/master/auc.ipynb

### Progress

Currently identified a variant that is around 4x faster when using ray:

```python3
from numba import jit


@jit(nopython=True)
def fast_auc(y_true, y_prob):
    y_true = y_true[np.argsort(y_prob)]
    nfalse = 0
    auc = 0
    n = len(y_true)
    for i in range(n):
        y_i = y_true[i]
        nfalse += (1 - y_i)
        auc += y_i * nfalse
    auc /= (nfalse * (n - nfalse))
    return auc


# Further speedup by removing redundant checks in AutoGluon `_ThresholdScorer`:
class _ThresholdScorer(Scorer):
    def _preprocess(self, y_true, y_pred, **kwargs):
        if isinstance(y_true, list):
            y_true = np.array(y_true)
        if isinstance(y_pred, list):
            y_pred = np.array(y_pred)
        return y_true, y_pred, kwargs

    ...

# Score functions that need decision values
roc_auc = make_scorer('roc_auc',
                      # classification_metrics.customized_binary_roc_auc_score,
                      classification_metrics.fast_auc,
                      greater_is_better=True,
                      needs_threshold=True)


```

# How do we speed it up?

We could try implementing accelerated variants. For example, we could use `cython` and implement the metrics in C, or try accelerators like `numba` or `scikit-learn-intelex`

# How many times do we call `eval_metric` during simulations?

**_TL;DR: 316 billion times_**

The eval_metric function is called `N*M` times for every greedy ensemble fit, where N is the number of greedy forward selection steps and M is the number of configs in the ensemble.

For a given simulation fold, we fit `A*B*C` greedy weighted ensembles, where A is the number of tasks, and B is the number of total configs, and C is the number of simulation steps.

Thus, the eval_metric is called roughly `A*B*C*N*M` times in a given simulation fold.

Lets put in the actual values (roughly) based on `bag_244`:

```
A = 1300
B = 608
C = 40
N = 100
M = C / 2 (average) = 20
```

Thus:

```
num_eval_metric_calls_per_fold = 1300 * 608 * 40 * 100 * 20
= 63,232,000,000
# Multiplied by 5 folds:
= 316,160,000,000
```

This means the eval_metric is called **316 billion times** in a 5-fold CV simulation. This will only increase if we add more datasets or configs.

**Comment by mglowacki100** [comment]
Hi @Innixma,
Here is alternative implementation of roc auc score: https://github.com/diditforlulz273/fastauc that could interest you.
Regarding rmse, in theory it could be replaced by mse for optimization, so no sqrt, but in practice obtained minima could differ.

**Comment by Innixma** [comment]
@mglowacki100 very good suggestion re roc_auc! This is actually exactly what I was looking into as well! You can see the result in #24.

Regarding `rmse`, I've found that `numba` does not speed it up, and it is already extremely fast in our current implementation, so probably unnecessary to optimize. `roc_auc` is >90% of the simulation cost now.

**Comment by Innixma** [comment]
#29 is now merged, which offers a 2-4x speedup in `roc_auc` calculation compared to #24.
